### ISSUE TITLE
Demo colors and fonts not correct on Linux

### ISSUE THREAD

**Issue by majorgreys** [lirios/fluid#129]
I tried cloning the repo and running the demo from Qt Creator as well as installing fluid under arch linux (liri-unstable/fluid-git 20170613.3e5b965-1) but I only get a window with wrong colors and fonts. This is on a fresh arch linux install and I am running KDE on Xorg. 

![image](https://user-images.githubusercontent.com/155673/27264653-03b92d00-5451-11e7-8f77-86bb8402789d.png)

Any ideas on what I might be missing?

**Comment by majorgreys** [comment]
I am new to Qt/QML so I might be missing something obvious. When I loaded up Liri under Wayland, this demo looked fine.

**Comment by plfiorini** [comment]
Looks like it's using the default style for some reason. Under Liri every app is always set to Material, outside Liri the demo should use Material if no other style is set but for some reason QQC2 thinks there is a style set.

I'm going to force the Material style for the demo.

**Comment by rmallah** [comment]
Hi Pier lets popularize the irc channel for such questions shall I submit a pull request for readme.md instructing people to come to irc channel instead of posting issues.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Pier Luigi Fiorini <notifications@github.com> Date: 6/19/17  09:41  (GMT+05:30) To: lirios/fluid <fluid@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [lirios/fluid] Demo colors and fonts not correct on Linux (#129) 
Looks like it's using the default style for some reason. Under Liri every app is always set to Material, outside Liri the demo should use Material if no other style is set but for some reason QQC2 thinks there is a style set.
I'm going to force the Material style for the demo.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lirios/fluid","title":"lirios/fluid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lirios/fluid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@plfiorini in #129: Looks like it's using the default style for some reason. Under Liri every app is always set to Material, outside Liri the demo should use Material if no other style is set but for some reason QQC2 thinks there is a style set.\r\n\r\nI'm going to force the Material style for the demo."}],"action":{"name":"View Issue","url":"https://github.com/lirios/fluid/issues/129#issuecomment-309334362"}}}
