### ISSUE TITLE
Why font.pixelSize?

### ISSUE THREAD

**Issue by luntik2012** [lirios/fluid#186]
Why don't you use font.pointSize instead of font.pixelSize? It seems more scalable if I'd like to run something on android etc.
(For example "TitleLabel" component)

**Comment by plfiorini** [comment]
`font.pixelSize` scales with DPI proportionally to other GUI elements, `font.pointSize` doesn't.

**Comment by luntik2012** [comment]
Cannot find something like that here:
https://doc-snapshots.qt.io/qt5-5.9/qml-qtquick-text.html#font.pixelSize-prop
Could you give some link about maping to gui elements?

**Comment by plfiorini** [comment]
"The fontPointSize property sets the point size in a device-independent manner. However, specifying fonts in points and other sizes in pixels causes problems, because points are independent of the display density. A frame around a string that looks correct on low DPI displays is likely to become too small on high DPI displays, causing the text to be clipped."

https://doc.qt.io/qt-5.10/scalability.html

**Comment by plfiorini** [comment]
"Applications using UI designs with fixed coordinates look small. The combination of font size specification in points and other sizes in pixels is particularly problematic since points are independent of the monitor resolution. For example, a frame of 40x20 pixels around the text "hello" using a 12pt font looks correct on low resolution monitors, but the frame will be too small on high DPI monitors, causing the text to be clipped."

http://doc.qt.io/qt-5/highdpi.html

**Comment by luntik2012** [comment]
Ok, thank you

**Comment by luntik2012** [comment]
Should I close this issue now or leave it here?

**Comment by plfiorini** [comment]
The issue can be closed, it will still be available search the issue tracker if someone has the same question.
