### ISSUE TITLE
Support qbs < 1.9

### ISSUE THREAD

**Issue by nickdiego** [lirios/fluid#240]
Hello, this is more of a question, Do you have any interest in supporting Qbs version < 1.9. I've recently ran into a problem when implementing a Qt5 app (using Fluid), targeting different Linux distros, including Ubuntu versions 16.x and 17.x, when when we tried to compile Fluid in distros like those it currently fails with Qbs errors (due to changes in version 1.9).

**Comment by plfiorini** [comment]
I raised the requirements first to qbs 1.9 and recently I did it for 1.11 because of qbs changes on the setup of the run environment. I don't remember exactly what introduced the qbs 1.9 requirement, I will take a look at the history and get back to you.

(It might not be something that is used by Fluid itself, but rather something used by qbs-shared).

**Comment by nickdiego** [comment]
> (It might not be something that is used by Fluid itself, but rather something used by qbs-shared).

Oh, you're right. Should I close this issue?

I've recently fix a similar issue (in `setupEnvironment` function) in library I was developing. I'll try to figure out a way to fix this in qbs-shared and try to send a pull request soon.

Thanks.

**Comment by pasdam** [comment]
Just an FYI: qbs is now deprecated.
https://blog.qt.io/blog/2018/10/29/deprecation-of-qbs/

**Comment by plfiorini** [comment]
Yep, see also https://github.com/lirios/lirios/issues/60
CMake is in almost every repository now.
