### ISSUE TITLE
QT min version 5.9

### ISSUE THREAD

**Issue by DevDorrejo** [lirios/fluid#297]
Hello, is possible to change the min version to QT 5.9?, because the majorities of others distro that use KDE are using 5.9.7/8 and not help to compile this UI framework, except with the full rolling release distros.

**Comment by plfiorini** [comment]
It's not possible because the `icon` group property was introduced with Qt 5.10, that is available since Dec 2017 (https://www.qt.io/qt5-10).

Fedora has Qt 5.12 (last LTS release), Debian unstable has always up to date Qt.
Then there are distributions with questionable choices. For example according to https://en.opensuse.org/Features_15.1#Qt_5, OpenSUSE 15.1 still uses a very old Qt 5.9.
They should really update to Qt 5.12 (last LTS) instead of keeping the previous LTS version. I don't even think that Qt 5.9 gets security updates anymore.
Ubuntu 19.04 (a GNOME distro that puts Qt in universe) on the other hand seems to use Qt 5.12, so that puts OpenSUSE even more on the spot.

**Comment by DevDorrejo** [comment]
Ok, thank you, i will try to communicate with the developers of opensuse, so maybe they can made the jump to QT 5.12.
