### ISSUE TITLE
Using qbs on android

### ISSUE THREAD

**Issue by raphaelcotty** [lirios/fluid#298]
With qbs 1.14 android support has improved.
Is there any plan to support qbs now?
I tried it but I get this error:
W Test: QQmlApplicationEngine failed to load component
W Test: qrc:/MemoVache.qml:9 module "Fluid.Controls" is not installed

But I see that the apk file has the module installed.

**Comment by plfiorini** [comment]
I love Qbs, it's far superior than any other build system other there.
However I don't see a clear leadership emerging from the mailing list and there is no concrete roadmap for the post TQtC life.  For this reason I don't think it's safe to try again, at least not just yet.
There are still .qbs files here are not being updated and were not deleted merely because, in case Qbs will be a viable option in the future, we don't have to start from scratch again.

That being said, I think that CMake supports Android and it's integrated with QtCreator.
I'm not sure how to do that (there are toolchain files) but it's possible, so it's a matter of reading some docs and doing it.

**Comment by raphaelcotty** [comment]
Me too I love qbs. And i am not willing to come back to cmake. I've used it enough in past to hate it.
Anyway, I just managed to make it work.
I had to do a couple of things:

1. Remove the Android.ndk.appStl: "gnustl_shared" properties as qt 5.13 builds with clang++

2. Remove the AbstractCard 1.0 AbstractCard.qml and ContactChip 1.1 ContactChip.qml line in imports/controls/qmldir

Are you interesting in updating the files?

**Comment by plfiorini** [comment]
If you can help maintaining .qbs files I would gladly keep Qbs around as an option even though the officially supported build system is CMake.

This means that I will accept PRs but I will focus my energy on CMake and Qbs is best effort.

**Comment by raphaelcotty** [comment]
ok,
Trying to build the demo but getting this error in demo.qbs:
fluid/src/demo/demo.qbs:7: avertissement : Item 'bundle' is not declared. Did you forget to add a Depends item?

When using the repository as a SubProject it works.

**Comment by plfiorini** [comment]
The `bundle` module is for Core Found bundle support: https://doc.qt.io/qbs/qml-qbsmodules-bundle.html
It didn't need any Depends back in qbs 1.9.x it should be available everywhere but useful on macOS
That what this line is for: https://github.com/lirios/fluid/blob/develop/src/demo/demo.qbs#L117
On macOS it creates a bundle instead of a normal executable

**Comment by plfiorini** [comment]
Since it's a module I guess Depends will work, probably for some obscure bug it was possible to use it without Depends before.
