### ISSUE TITLE
Ubuntu Touch

### ISSUE THREAD

**Issue by delijati** [lirios/fluid#82]
Is this working with ubuntu touch convergence?

**Comment by tim-sueberkrueb** [comment]
Hey @delijati, can you be more specific?
This library cannot be used practically for developing Apps for Ubuntu Phones which are on the market right now. Those phones are based on the click package format and ship with Qt 5.4. However, Fluid requires Qt >= Qt 5.8.
In the future, Ubuntu images will switch to snap which gives developers more flexibility when it comes to including custom Qt binaries. We started working on a platform snap which will allow us to bundle Fluid + Qt 5.8 + other libraries for future Liri app snaps. So, technically, yes, Fluid should work good in combination with future Ubuntu personal images based on snap.
From the usability perspective, yes, Fluid also fits Ubuntu's convergence goal. We already added some components which enable building more responsive QtQuick applications.

**Comment by delijati** [comment]
Hey @tim-sueberkrueb thanks for your detailed answer. I was trying to build https://github.com/davidar/tensor for my BQ 4.5 phone but than is was stuck, because of the [QtQuick.Controls](https://github.com/davidar/tensor/issues/4) issue. As for `snap` is it true that it will only support `arm64` and the BQ phone  (`armhf`) will be not updated? So i'm not sure if should just wait until `snap` update is done or just rewrite the QML parts to plain ubuntu touch without a cross platform QML framework.

**Comment by tim-sueberkrueb** [comment]
Hey @delijati.

> As for snap is it true that it will only support arm64 and the BQ phone (armhf) will be not updated?

While snap does work on `armhf` most of the current devices won't probably updated because of the underlying software and android bits, to my understanding.

What you want is getting `QtQuick Controls 1` (QtQuick Controls 2 require Qt >= 5.7) working on Ubuntu Phone. This is perfectly possible with click (note that snap will make what you want to archive much easier though):

Have a look at https://github.com/tim-sueberkrueb/mygus-touch. This is a deprecated project of mine which was successfully published in the Ubuntu Store using QtQuick Controls + QML Material.
You should have a look at:
* `get_libs.py`: This script allows you to fetch `QtQuick.Controls` and moves it to `lib/arch ...` [1]
* `*.qmlproject`: https://github.com/tim-sueberkrueb/mygus-touch/blob/master/mygus-ubuntu-touch.qmlproject#L58

[1] it also fetches `pyotherside` but you'll manage to remove the relevant parts.
Good luck!

**Comment by delijati** [comment]
Hej @tim-sueberkrueb,

thanks thats perfect. I will take a look into it.

**Comment by tim-sueberkrueb** [comment]
@plfiorini I think this can be closed (I have no access for this repository).
@delijati if you have any further questions, feel free to send me an email (contact@timsueberkrueb.io).
