### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by magnus-gross** [lirios/fluid#84]
I compiled using qmake. Executing the demo in build/src/demo results in:
```QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:109 Type LayoutComponents unavailable
qrc:/qml/LayoutComponents.qml:73 Type AutomaticGridPage unavailable
qrc:/qml/Pages/Layouts/AutomaticGridPage.qml:17 module "Fluid.Layouts" is not installed```

**Comment by plfiorini** [comment]
For some reason build/src/demo doesn't import QML from the build directory I haven't figured out yet how to do it. Meanwhile you should install and everything should work then.

**Comment by magnus-gross** [comment]
So what do I have to do to start it? I already did `sudo make install`

**Comment by plfiorini** [comment]
@magnus-gross does it still failed if you type `fluid-demo` ?

**Comment by magnus-gross** [comment]
From what directory? I pulled the latest commits and compiled with the qmake makefile. The same errors are returned if I run `./fluid-demo` from the build/src/demo directory

**Comment by plfiorini** [comment]
If you installed without setting the LIRI_INSTALL_PREFIX the files are likely to be installed in /usr/local so if you want to run `fluid-demo` you need to set all the Qt env vars for `/usr/local`.

If you want to perform a system-wide installation pass ```LIRI_INSTALL_PREFIX=/usr```

**Comment by plfiorini** [comment]
@magnus-gross but that is risky if you install Fluid from distro packages later on or if you update sources because files are going to be mixed so the best would be to configure like this:

```
mkdir build; cd build
qmake LIRI_INSTALL_PREFIX=/opt/liri ../fluid.pro
make
make install # use sudo if necessary
```

And then set the env vars like this, create `~/lenv`:

```
LIRIDIR=/opt/liri

export LD_LIBRARY_PATH=$LIRIDIR/lib:$LD_LIBRARY_PATH
export XDG_DATA_DIRS=$LIRIDIR/share:/usr/local/share:/usr/share:~/.local/share:~/.local/share/flatpak/exports/share
export XDG_CONFIG_DIRS=$LIRIDIR/etc/xdg:/etc/xdg
export QT_PLUGIN_PATH=$LIRIDIR/lib/plugins
export QML2_IMPORT_PATH=$LIRIDIR/lib/qml:$QML2_IMPORT_PATH
export PATH=$LIRIDIR/bin:$PATH
export QT_XCB_GL_INTEGRATION=xcb_egl
```

Source the environment file and run fluid-demo:

```
source ~/lenv
/opt/liri/bin/fluid-demo
```

**Comment by plfiorini** [comment]
Otherwise there is now a `fluid-demo.pro` project that you can open from QtCreator. It will statically build Fluid and the demo, no system-wide installation necessary. Just open the project, configure, build and run.


Of course without a system-wide installation you won't be able to use Fluid from another project

**Comment by plfiorini** [comment]
Otherwise there is now a `fluid-demo.pro` project that you can open from QtCreator. It will statically build Fluid and the demo, no system-wide installation necessary. Just open the project, configure, build and run.

This project was made so that users can quickly try the demo without the usual Linux and Qt installation hiccups (paths, env vars, ...).

Of course without a system-wide installation you won't be able to use Fluid from another project

**Comment by magnus-gross** [comment]
Thanks a lot, I will try the dynamically linked installation when I am home and report back, if it works. Please consider putting these instructions in your readme. :)

**Comment by magnus-gross** [comment]
Ok, I just tried it again with the new installation instructions and now it works. :)
Btw very good job, I really like the components, especially the configurable bottom sheet is really neat.
Keep up the good work! :)

**Comment by plfiorini** [comment]
Thanks I'm glad that you liked it :)
